# Generated by Django 4.2.10 on 2024-02-20 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_note_last_edited_by_alter_note_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_editor_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
