# Generated by Django 4.2.10 on 2024-02-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0005_alter_note_last_edited_by_alter_note_owner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
